language: android
dist: trusty

android:
    licenses:
        - android-sdk-license-.+
        - '.+'
    components:
        - platform-tools
        - tools
        - build-tools-25.0.2
        - android-29
        - extra-google-m2repository

script:
    - "./gradlew check"
