language: android
dist: trusty
android:
    components:
        - build-tools-29.0.2
        - android-29
        - platform-tools
        - tools
        - add-on
        - extra
    licenses:
        - android-sdk-license-.+
        - '.+'

script:
    - "./gradlew check"
